######################################################################
# Automatically generated by qmake (2.01a) lun. 7. mai 11:59:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += console
QT += network

# Input
SOURCES += AsciiArt.cpp
