######################################################################
# Automatically generated by qmake (2.01a) Sun May 6 18:49:07 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += AsciiArt.cpp
