######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 14 03:04:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += DancingWiththeGooglers.cpp
