######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 28 02:55:06 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += A.cpp
