######################################################################
# Automatically generated by qmake (2.01a) Sun May 6 16:35:50 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += JewelsAndStones.cpp
