######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 13 19:19:22 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += FileFix-it.cpp
