######################################################################
# Automatically generated by qmake (2.01a) Sat May 5 17:49:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += base.cpp
