######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 14 01:39:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += SpeakingInTongues.cpp
