######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 21 22:27:19 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += IrregularExpressions.cpp
