######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 14 04:45:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += RecycledNumbers.cpp
