######################################################################
# Automatically generated by qmake (2.01a) Sun May 6 11:26:47 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += base.cpp
