######################################################################
# Automatically generated by qmake (2.01a) Sun May 6 17:19:06 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += LuckyLuckyNumber.cpp
